### ISSUE TITLE
Store the points and titles of each user.

### ISSUE THREAD

**Issue by cparzy** [LaFrimousse/SwengProject#149]

**Comment by hedi-sassi** [comment]
@LaFrimousse  t'as pas besoin de faire cette partie je pense. On peut la faire avec la DB que j'ai car j'ai déjà les points du gars sur la DB et j'ai une fonction pour dériver le titre à partir des points. Mais sinon on peut garder ce que t'as fait et adapter un peu.

Donc soit:

1) tu peux continuer à mettre ces 2 champs dans ta DB pour les users si tu veux (pour la cohérance) mais il faudra (quand on update les points dans l'activité que Simon fait) push ces changements sur ta DB.

ou

2) t'as pas besoin de les ajouter et on utilisera ma DB pour montrer ces infos sur le profil utilisateur (pour qu'il puisse voir ses points et son titre)

Pour moi c'est égal.

**Comment by LaFrimousse** [comment]
J’ai déjà implémenté l’option un sur ma branche actuelle faut juste pouvoir
passer api 24 et je peux mettre les tests et push!

Le jeu. 15 nov. 2018 à 15:10, hedi-sassi <notifications@github.com> a
écrit :

**Comment by hedi-sassi** [comment]
OK alors on fait ça
