### ISSUE TITLE
Configure Travis CI in a new project

### ISSUE THREAD

**Issue by LaFrimousse** [LaFrimousse/SwengProject#5]

**Comment by LaFrimousse** [comment]
@dialexo @Theyiot
 Bonjour vous deux, comme je suis le propriétaire du repo SwengProject, c'est à moi de configurer Jacoco, Travis CI etc, bref de suivre la procédure décrite dans BootCamp. 
Je suis actuellement coincé avec Travis CI, et je me demandais si vous pouviez m'aider à distance ou si on attend de se revoir la prochaine séance.
Voici le rapport d'erreur envoyé par Travis: 
 https://travis-ci.org/LaFrimousse/SwengProject/builds/434937555
Bonne suite de weekend à vous deux !

**Comment by dialexo** [comment]
Salut! De ce que je vois tu as mal configuré ton [.travis.yml. ](https://github.com/LaFrimousse/SwengProject/blob/master/.travis.yml). 
L'indentation définit le scope des config, donc là c'est comme si ta config android était null. Regarde [l'exemple du Bootcamp](https://github.com/sweng-epfl/Bootcamp#configure-travis-ci-through-your-repository)

**Comment by LaFrimousse** [comment]
@dialexo  
Merci pour ta réponse, le fichier était visiblement mal configuré MAIS: 
le test en ligne ne passe toujours pas !
https://travis-ci.org/LaFrimousse/SwengProject
As tu une idée de ce qui peut causer la faute malgré le nouveau .travis.yml ? 
Bonne journée
